kind: pipeline
type: docker
name: default

steps:
  - name: 打包
    image: node:16.17.0
    pull: if-not-exists # always never
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn
      - yarn run build:production
      - cp -fr build/* .. # 不复制下，就映射不了
    volumes:
      - name: cache
        path: /drone

volumes:
  - name: cache
    host:
      path: /home/data/nfs/k8s/ssd/rift-rift-client-dist-pvc-68f918ba-326c-42a5-8833-9e60b513c29c    